---
name: CI

on: [push, pull_request]

# Jobs run in parallel (unless linked by `needs`)
jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # Filters
      # - name: PR-filter
      #   uses: actions/bin/filter@master
      #   args: 'ref refs/pulls/*'

      # - name: master-filter
      #   uses: actions/bin/filter@master
      #   args: 'branch master'

      # Actions
      - name: markdownlint
        uses: sunjon/github_actions/actions/markdownlint@master
        continue-on-failure: true

      - name: yamllint
        uses: sunjon/github_actions/actions/yamllint@master
        continue-on-failure: true

      # - name: "bash-lint"
      #   uses: "sunjon/actions/bash@master"

      # - name: "hadolint"
      #   uses: "sunjon/actions/hadolint@master"

      # - name: "kubeval"
      #   uses: "sunjon/actions/kubeval@master"


      # - name: "rubocop"
      #   uses: "sunjon/actions/rubocop@master"
      #   run: ["master filter"]

      # - name: "shellcheck"
      #   uses: "sunjon/actions/shellcheck@master"

      # - name: "shfmt-lint"
      #   uses: "sunjon/actions/shfmt@master"
      #   run: ["master filter"]
