Name: Lint RTFM Markdown documents

on: [push]

jobs:
  build:
    # Job name is Greeting
    name: # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # Create shallow clone of the repository
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/validate
        with:
          linters: "mdl"
      # This step uses GitHub's hello-world-javascript-action:
      # https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Mona the Octocat"
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
